module.exports = {
  DEFAULT_PROJECTION: 'globe',
  DEFAULT_STYLE: 'Standard',
  DEFAULT_DARK_FEATURE_COLOR: '#555',
  DEFAULT_LIGHT_FEATURE_COLOR: '#e8e8e8',
  DEFAULT_SATELLITE_FEATURE_COLOR: '#00f900',
  WALKABLE_AREA_POINT_DENSITY: 0.2,
  WALKABLE_AREA_POINT_RADIUS: 2,
  WALKABLE_AREA_POINT_COLOR: [255, 0, 0, 100]
};
